[package]
name = "roman"
version = "0.1.0"
authors = ["Jud White <github@judsonwhite.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
